# Generated by Django 3.0.7 on 2023-11-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20231111_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
    ]
