# Generated by Django 3.0.7 on 2023-11-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_remove_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
